### ISSUE TITLE
WPF-AutoComplete-TextBox doesn't exist anymore

### ISSUE THREAD

**Issue by billr1** [porohkun/TimeLogger#5]
It appears the version of WPF-AutoComplete-TextBox used in this project no longer exists. This project expects WPF-AutoComplete-TextBox\WpfControls\... to be present, but the current repo on GitHub (if it's the same control) seems to have renamed things so it's now WPF-AutoComplete-TextBox\AutoCompleteTextBox\AutoCompleteTextBox\....

**Comment by porohkun** [comment]
Oh... All this time it was a local fork. My bad. Added this repository as a submodule. Thanks for pointing this.

**Comment by billr1** [comment]
On Fri, 31 May 2019 14:42:10 -0700
Pavel <notifications@github.com> wrote:

> Oh... All this time it was a local fork. My bad. Added this
> repository as a submodule. Thanks for pointing this.
> 

You're welcome. Thanks for the quick response! I'll do a pull and try
building again on Monday.

	-Bill
